import {
  INodeType,
  INodeTypeDescription,
  NodeConnectionTypes,
} from 'n8n-workflow';

export class Localith implements INodeType {
  description: INodeTypeDescription = {
    displayName: 'Localith',
    name: 'localith',
    icon: 'file:localith.svg',
    group: ['transform'],
    version: 1,
    subtitle: '={{$parameter["operation"] + ": " + $parameter["resource"]}}',
    description: 'Interact with the Localith API',
    defaults: { name: 'Localith' },
    inputs: [NodeConnectionTypes.Main],
    outputs: [NodeConnectionTypes.Main],
    credentials: [{ name: 'localithApi', required: true }],
    requestDefaults: {
      baseURL: 'https://embedsocial.com/app/api',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
    },
    properties: [
      {
        displayName: 'Resource',
        name: 'resource',
        type: 'options',
        noDataExpression: true,
        options: [
          { name: 'Content Publishing Media', value: 'contentPublishingMedia' },
          { name: 'Item', value: 'item' },
          { name: 'Listing', value: 'listing' },
          { name: 'Listing Item Metric', value: 'listingItemMetrics' },
          { name: 'Listing Metric', value: 'listingMetrics' },
        ],
        default: 'listing',
      },

      // ─── ITEM ────────────────────────────────────────────────────────────────
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['item'] } },
        options: [
          {
            name: 'Get Many',
            value: 'getAll',
            description: 'Retrieve the collection of items (reviews)',
            action: 'Get many items',
            routing: { request: { method: 'GET', url: '/rest/v1/items' } },
          },
        ],
        default: 'getAll',
      },
      {
        displayName: 'Filters',
        name: 'filters',
        type: 'collection',
        placeholder: 'Add Filter',
        default: {},
        displayOptions: { show: { resource: ['item'], operation: ['getAll'] } },
        options: [
          {
            displayName: 'Page',
            name: 'page',
            type: 'number',
            typeOptions: { minValue: 1 },
            default: 1,
            routing: { send: { type: 'query', property: 'page' } },
          },
          {
            displayName: 'Page Size',
            name: 'pageSize',
            type: 'number',
            typeOptions: { minValue: 1, maxValue: 100 },
            default: 10,
            routing: { send: { type: 'query', property: 'pageSize' } },
          },
          {
            displayName: 'Source ID',
            name: 'sourceId',
            type: 'string',
            default: '',
            description: 'Filter by source ID(s). Comma-separated for multiple values.',
            routing: { send: { type: 'query', property: 'sourceId' } },
          },
          {
            displayName: 'Sort',
            name: 'sort',
            type: 'string',
            default: '',
            description: 'Sort order. Use +fieldName for ascending, -fieldName for descending. Comma-separate multiple fields, e.g. "-originalCreatedOn".',
            routing: { send: { type: 'query', property: 'sort' } },
          },
        ],
      },

      // ─── LISTING ──────────────────────────────────────────────────────────────
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['listing'] } },
        options: [
          {
            name: 'Get Many',
            value: 'getAll',
            description: 'Retrieve the collection of listings',
            action: 'Get many listings',
            routing: { request: { method: 'GET', url: '/rest/v1/listings' } },
          },
          {
            name: 'Get',
            value: 'get',
            description: 'Retrieve a single listing by ID',
            action: 'Get a listing',
            routing: {
              request: {
                method: 'GET',
                url: '=/rest/v1/listings/{{$parameter["listingId"]}}',
              },
            },
          },
          {
            name: 'Update',
            value: 'update',
            description: 'Update a listing by ID',
            action: 'Update a listing',
            routing: {
              request: {
                method: 'PATCH',
                url: '=/rest/v1/listings/{{$parameter["listingId"]}}',
              },
            },
          },
        ],
        default: 'getAll',
      },
      {
        displayName: 'Filters',
        name: 'filters',
        type: 'collection',
        placeholder: 'Add Filter',
        default: {},
        displayOptions: { show: { resource: ['listing'], operation: ['getAll'] } },
        options: [
          {
            displayName: 'Address',
            name: 'address',
            type: 'string',
            default: '',
            description: 'Filter by listing address',
            routing: { send: { type: 'query', property: 'address' } },
          },
          {
            displayName: 'Name',
            name: 'name',
            type: 'string',
            default: '',
            description: 'Filter by listing name',
            routing: { send: { type: 'query', property: 'name' } },
          },
          {
            displayName: 'Page',
            name: 'page',
            type: 'number',
            typeOptions: { minValue: 1 },
            default: 1,
            routing: { send: { type: 'query', property: 'page' } },
          },
          {
            displayName: 'Page Size',
            name: 'pageSize',
            type: 'number',
            typeOptions: { minValue: 1, maxValue: 100 },
            default: 10,
            routing: { send: { type: 'query', property: 'pageSize' } },
          },
          {
            displayName: 'Sort',
            name: 'sort',
            type: 'string',
            default: '',
            description: 'Sort order. Use +fieldName for ascending, -fieldName for descending.',
            routing: { send: { type: 'query', property: 'sort' } },
          },
        ],
      },
      {
        displayName: 'Listing ID',
        name: 'listingId',
        type: 'string',
        required: true,
        default: '',
        description: 'The ID of the listing',
        displayOptions: {
          show: { resource: ['listing'], operation: ['get', 'update'] },
        },
      },
      {
        displayName: 'Update Fields',
        name: 'updateFields',
        type: 'collection',
        placeholder: 'Add Field',
        default: {},
        displayOptions: { show: { resource: ['listing'], operation: ['update'] } },
        options: [
          {
            displayName: 'City',
            name: 'city',
            type: 'string',
            default: '',
            routing: { send: { type: 'body', property: 'address.city' } },
          },
          {
            displayName: 'Country',
            name: 'country',
            type: 'string',
            default: '',
            description: 'Country code, e.g. "MK"',
            routing: { send: { type: 'body', property: 'address.country' } },
          },
          {
            displayName: 'Description',
            name: 'description',
            type: 'string',
            typeOptions: { rows: 3 },
            default: '',
            routing: { send: { type: 'body', property: 'description' } },
          },
          {
            displayName: 'Name',
            name: 'name',
            type: 'string',
            default: '',
            routing: { send: { type: 'body', property: 'name' } },
          },
          {
            displayName: 'Phone Number',
            name: 'phoneNumber',
            type: 'string',
            default: '',
            routing: { send: { type: 'body', property: 'phoneNumber' } },
          },
          {
            displayName: 'Street Address',
            name: 'streetLines',
            type: 'string',
            default: '',
            routing: { send: { type: 'body', property: 'address.streetLines[0]' } },
          },
          {
            displayName: 'Website URL',
            name: 'websiteUrl',
            type: 'string',
            default: '',
            routing: { send: { type: 'body', property: 'websiteUrl' } },
          },
        ],
      },

      // ─── LISTING METRICS ──────────────────────────────────────────────────────
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['listingMetrics'] } },
        options: [
          {
            name: 'Get Many',
            value: 'getAll',
            description: 'Retrieve daily listing metrics summarized data',
            action: 'Get listing metrics',
            routing: { request: { method: 'GET', url: '/rest/v1/listing_metrics' } },
          },
        ],
        default: 'getAll',
      },
      {
        displayName: 'Start Date',
        name: 'startDate',
        type: 'string',
        required: true,
        default: '',
        placeholder: '25-08-2024',
        description: 'Start date in DD-MM-YYYY format',
        displayOptions: { show: { resource: ['listingMetrics'], operation: ['getAll'] } },
        routing: { send: { type: 'query', property: 'startDate' } },
      },
      {
        displayName: 'End Date',
        name: 'endDate',
        type: 'string',
        required: true,
        default: '',
        placeholder: '24-08-2025',
        description: 'End date in DD-MM-YYYY format',
        displayOptions: { show: { resource: ['listingMetrics'], operation: ['getAll'] } },
        routing: { send: { type: 'query', property: 'endDate' } },
      },
      {
        displayName: 'Filters',
        name: 'filters',
        type: 'collection',
        placeholder: 'Add Filter',
        default: {},
        displayOptions: { show: { resource: ['listingMetrics'], operation: ['getAll'] } },
        options: [
          {
            displayName: 'Source ID',
            name: 'sourceId',
            type: 'string',
            default: '',
            description: 'Optional source ID(s). Comma-separated for multiple values.',
            routing: { send: { type: 'query', property: 'sourceId' } },
          },
          {
            displayName: 'Page',
            name: 'page',
            type: 'number',
            typeOptions: { minValue: 1 },
            default: 1,
            routing: { send: { type: 'query', property: 'page' } },
          },
          {
            displayName: 'Page Size',
            name: 'pageSize',
            type: 'number',
            typeOptions: { minValue: 1, maxValue: 100 },
            default: 10,
            routing: { send: { type: 'query', property: 'pageSize' } },
          },
        ],
      },

      // ─── LISTING ITEM METRICS ─────────────────────────────────────────────────
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['listingItemMetrics'] } },
        options: [
          {
            name: 'Get Many',
            value: 'getAll',
            description: 'Retrieve reviews metrics summarized data',
            action: 'Get listing item metrics',
            routing: { request: { method: 'GET', url: '/rest/v1/listing_item_metrics' } },
          },
        ],
        default: 'getAll',
      },
      {
        displayName: 'Start Date',
        name: 'startDate',
        type: 'string',
        required: true,
        default: '',
        placeholder: '25-08-2024',
        description: 'Start date in DD-MM-YYYY format',
        displayOptions: { show: { resource: ['listingItemMetrics'], operation: ['getAll'] } },
        routing: { send: { type: 'query', property: 'startDate' } },
      },
      {
        displayName: 'End Date',
        name: 'endDate',
        type: 'string',
        required: true,
        default: '',
        placeholder: '24-08-2025',
        description: 'End date in DD-MM-YYYY format',
        displayOptions: { show: { resource: ['listingItemMetrics'], operation: ['getAll'] } },
        routing: { send: { type: 'query', property: 'endDate' } },
      },
      {
        displayName: 'Filters',
        name: 'filters',
        type: 'collection',
        placeholder: 'Add Filter',
        default: {},
        displayOptions: { show: { resource: ['listingItemMetrics'], operation: ['getAll'] } },
        options: [
          {
            displayName: 'Source ID',
            name: 'sourceId',
            type: 'string',
            default: '',
            description: 'Optional source ID(s). Comma-separated for multiple values.',
            routing: { send: { type: 'query', property: 'sourceId' } },
          },
          {
            displayName: 'Page',
            name: 'page',
            type: 'number',
            typeOptions: { minValue: 1 },
            default: 1,
            routing: { send: { type: 'query', property: 'page' } },
          },
          {
            displayName: 'Page Size',
            name: 'pageSize',
            type: 'number',
            typeOptions: { minValue: 1, maxValue: 100 },
            default: 10,
            routing: { send: { type: 'query', property: 'pageSize' } },
          },
        ],
      },

      // ─── CONTENT PUBLISHING MEDIA ─────────────────────────────────────────────
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['contentPublishingMedia'] } },
        options: [
          {
            name: 'Publish / Schedule',
            value: 'publish',
            description: 'Publish or schedule content publishing media posts',
            action: 'Publish or schedule a media post',
            routing: {
              request: {
                method: 'POST',
                url: '/rest/v1/content_publishing_media',
              },
            },
          },
        ],
        default: 'publish',
      },
      {
        displayName: 'Type',
        name: 'type',
        type: 'options',
        required: true,
        default: 'update',
        displayOptions: { show: { resource: ['contentPublishingMedia'], operation: ['publish'] } },
        options: [
          { name: 'Update', value: 'update' },
          { name: 'Event', value: 'event' },
          { name: 'Offer', value: 'offer' },
        ],
        description: 'The type of post to publish',
        routing: { send: { type: 'body', property: 'type' } },
      },
      {
        displayName: 'Source IDs',
        name: 'sourceIds',
        type: 'string',
        required: true,
        default: '',
        description: 'Comma-separated list of source IDs to publish to',
        displayOptions: { show: { resource: ['contentPublishingMedia'], operation: ['publish'] } },
        routing: {
          send: {
            type: 'body',
            property: 'sourceIds',
            value: '={{$value.split(",").map(s => s.trim()).filter(Boolean)}}',
          },
        },
      },
      {
        displayName: 'Post Fields',
        name: 'postFields',
        type: 'collection',
        placeholder: 'Add Field',
        default: {},
        displayOptions: { show: { resource: ['contentPublishingMedia'], operation: ['publish'] } },
        options: [
          {
            displayName: 'Caption Text',
            name: 'captionText',
            type: 'string',
            typeOptions: { rows: 3 },
            default: '',
            routing: { send: { type: 'body', property: 'captionText' } },
          },
          {
            displayName: 'CTA Type',
            name: 'ctaType',
            type: 'options',
            default: 'book',
            options: [
              { name: 'Book', value: 'book' },
              { name: 'Call', value: 'call' },
              { name: 'Learn More', value: 'learn_more' },
              { name: 'Order', value: 'order' },
              { name: 'Shop', value: 'shop' },
              { name: 'Sign Up', value: 'sign_up' },
            ],
            routing: { send: { type: 'body', property: 'ctaType' } },
          },
          {
            displayName: 'CTA URL',
            name: 'ctaUrl',
            type: 'string',
            default: '',
            routing: { send: { type: 'body', property: 'ctaUrl' } },
          },
          {
            displayName: 'End Date',
            name: 'endDate',
            type: 'string',
            default: '',
            placeholder: '2026-03-18T00:00:00Z',
            description: 'Event/offer end date. Format: 2026-03-18T00:00:00Z (UTC).',
            routing: { send: { type: 'body', property: 'endDate' } },
          },
          {
            displayName: 'Image URLs',
            name: 'imageUrls',
            type: 'string',
            default: '',
            description: 'Comma-separated list of image URLs',
            routing: {
              send: {
                type: 'body',
                property: 'imageUrls',
                value: '={{$value.split(",").map(u => u.trim()).filter(Boolean)}}',
              },
            },
          },
          {
            displayName: 'Scheduled On',
            name: 'scheduledOn',
            type: 'string',
            default: '',
            placeholder: '2026-03-12T00:00:00Z',
            description: 'When to publish. Leave empty to publish immediately. Format: 2026-03-12T00:00:00Z (UTC)',
            routing: { send: { type: 'body', property: 'scheduledOn' } },
          },
          {
            displayName: 'Start Date',
            name: 'startDate',
            type: 'string',
            default: '',
            placeholder: '2026-03-12T00:00:00Z',
            description: 'Event/offer start date. Format: 2026-03-12T00:00:00Z (UTC).',
            routing: { send: { type: 'body', property: 'startDate' } },
          },
          {
            displayName: 'Title',
            name: 'title',
            type: 'string',
            default: '',
            routing: { send: { type: 'body', property: 'title' } },
          },
          {
            displayName: 'Voucher Code',
            name: 'voucherCode',
            type: 'string',
            default: '',
            routing: { send: { type: 'body', property: 'voucherCode' } },
          },
        ],
      },
    ],
    usableAsTool: true,
  };
}
